### ISSUE TITLE
System.InvalidOperationException: 'Sequence contains no elements'

### ISSUE THREAD

**Issue by t0b4cc0** [ooples/OoplesFinance.StockIndicators#2]
Hello!

I wanted to try out this awesome library. Testing the first indicator, Bollinger Bands like this i get the following error:

`System.InvalidOperationException: 'Sequence contains no elements'`

Stacktrace: 
```
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Average(IEnumerable`1 source)
   at OoplesFinance.StockIndicators.Calculations.CalculateSimpleMovingAverage(StockData stockData, Int32 length)
   at OoplesFinance.StockIndicators.Helpers.CalculationsHelper.GetMovingAverageList(StockData stockData, MovingAvgType movingAvgType, Int32 length, List`1 customValuesList)
   at OoplesFinance.StockIndicators.Calculations.CalculateBollingerBands(StockData stockData, MovingAvgType maType, Int32 length, Decimal stdDevMult)
   at OoplesFinance.StockIndicators.Calculations.CalculateBollingerBands(StockData stockData)
   at antihodl2core.LearnDataGenerator.SkenderMinutes.Run() in F:\src\antihodl2\antihodl2core\LearnDataGenerator\SkenderMinutes.cs:line 104
   at antihodl2core.Form1.<learningDataGenerator_Click>d__7.MoveNext() in F:\src\antihodl2\antihodl2core\Form1.cs:line 69
```

Not sure what could be missing here.

![image](https://user-images.githubusercontent.com/9497253/151423165-01b51dbb-558e-480e-87a8-b6f03dc3e5b7.png)

![image](https://user-images.githubusercontent.com/9497253/151423302-4c19e010-8db0-4676-862c-f2cf7109c887.png)

**Comment by ooples** [comment]
I'm checking this issue now and I will get back to you as soon as I figure
out the reason

**Comment by t0b4cc0** [comment]
wow that was a fast reply.

same situation with others
![image](https://user-images.githubusercontent.com/9497253/151423877-d92ff526-1694-46a4-ab72-7c551ede136f.png)

i am in a .net 6 project if that matters

**Comment by ooples** [comment]
I like to respond quickly so you know I'm on top of things. I believe I
know where the issue is coming from and working on confirming my
suspicions. I introduced some new code that could be breaking everything.

Franklin

**Comment by ooples** [comment]
Alright I just uploaded a new version 1.0.22 with the fix for this critical
bug you found. Please confirm if this fixes the issue for you

Franklin

**Comment by t0b4cc0** [comment]
wow this is impressive! It works! 
The opposite of the mass of unmaintained abandoned repos I had to deal with.
I tested a few indicators. The functions return results that seem to make sense.
This is really a joy. I also adore how the library is structured/the way I can use it.

Thanks alot!

**Comment by ooples** [comment]
@t0b4cc0 I really appreciate the feedback. I have over 400 indicators so far but over 400 or so that I have written already and been working very hard on getting all of them ported over to this library format. I'm glad you enjoy it and I hope that you will help me spread the word since this is a brand new project
