### ISSUE TITLE
CalculateInsyncIndex throws the following exception

### ISSUE THREAD

**Issue by HamzaAhmedZia7** [ooples/OoplesFinance.StockIndicators#43]
Greetings Franklin,

This code
```
var bars = stockHistoryDaily[@"RELIANCE"];
var stockData = new StockData(bars.Select(x => x.Open), bars.Select(x => x.High), bars.Select(x => x.Low), bars.Select(x => x.Close), bars.Select(x => x.Volume), bars.Select(x => x.DateTime));
var insyncResults = stockData.CalculateInsyncIndex();
var insyncIndex = insyncResults.OutputValues["Iidx"];
```
produces this exception
```
OoplesFinance.StockIndicators.Exceptions.CalculationException: Calculations based off of BollingerBands can't be completed because this indicator doesn't have a single output.
   at OoplesFinance.StockIndicators.Helpers.CalculationsHelper.GetInputValuesList(StockData stockData)
   at OoplesFinance.StockIndicators.Calculations.CalculateDetrendedPriceOscillator(StockData stockData, MovingAvgType maType, Int32 length)
   at OoplesFinance.StockIndicators.Calculations.CalculateInsyncIndex(StockData stockData, MovingAvgType maType, Int32 fastLength, Int32 slowLength, Int32 signalLength, Int32 emoLength, Int32 mfiLength, Int32 bbLength, Int32 cciLength, Int32 dpoLength, Int32 rocLength, Int32 rsiLength, Int32 stochLength, Int32 stochKLength, Int32 stochDLength, Int32 smaLength, Double stdDevMult, Double divisor)
   at Program.<Main>$(String[] args) in 
```

in method **CalculateDetrendedPriceOscillator** at line _CalculationsHelper.GetInputValuesList(stockData).inputList;_
```public static StockData CalculateDetrendedPriceOscillator(
      this StockData stockData,
      MovingAvgType maType = MovingAvgType.SimpleMovingAverage,
      int length = 20)
    {
      List<double> doubleList = new List<double>();
      List<Signal> signalList = new List<Signal>();
      List<double> inputList = CalculationsHelper.GetInputValuesList(stockData).inputList;
      int num1 = MathHelper.MinOrMax(checked ((int) Math.Ceiling(unchecked ((double) length / 2.0 + 1.0))));
      List<double> movingAverageList = CalculationsHelper.GetMovingAverageList(stockData, maType, length, inputList);
      int index = 0;
```

It is called by this code
``` double stdDevMult1 = num1;
      List<double> customValuesList5 = stockData1.CalculateBollingerBands(length: length, stdDevMult: stdDevMult1).CustomValuesList;
      List<double> customValuesList6 = stockData.CalculateDetrendedPriceOscillator(length: dpoLength).CustomValuesList;
      List<double> customValuesList7 = stockData.CalculateRateOfChange(rocLength).CustomValuesList;
```

I am trying out your excellent humongous library. :-)

**Comment by ooples** [comment]
@HamzaAhmedZia7 I will add the test project later but I did see the reason for the exception and provided a fix so if you can please get the latest and confirm that it works now

**Comment by HamzaAhmedZia7** [comment]
@ooples 

With the latest the exception is gone but the iidx values are not consistent with what is on tradingview.

An example of this is RELIANCE on Friday August 04, 2023. The Insync index on Trading View is approx 45.02. 
![Screenshot_20230809_111944](https://github.com/ooples/OoplesFinance.StockIndicators/assets/140293889/1ada8f26-a284-4260-83e4-9c3ab871785b)


The Insync Index produced by this library is 60. 

![Screenshot_20230809_113103](https://github.com/ooples/OoplesFinance.StockIndicators/assets/140293889/16253b3f-4e97-4650-b610-40a5d01baff4)

Did you take into account both the lower and upper bands in the calculation?

**Comment by HamzaAhmedZia7** [comment]
I have sourced the data for this stock from TradingView website so there should be no discrepencies

**Comment by HamzaAhmedZia7** [comment]
Even Bollinger Bands calculations do not match
RELIANCE on Friday August 04, 2023. The bollinger bands values are as in the screenshot below
![Screenshot_20230809_135253](https://github.com/ooples/OoplesFinance.StockIndicators/assets/140293889/79c77330-4c77-45e3-ad11-0fdabc077d7a)

The Bollinger band produced by the library is way off.

Upper Band
![Screenshot_20230809_135550](https://github.com/ooples/OoplesFinance.StockIndicators/assets/140293889/e72f07f0-d80e-46f9-9abe-eb3a94365b11)



Middle Band
![Screenshot_20230809_135737](https://github.com/ooples/OoplesFinance.StockIndicators/assets/140293889/fdec7341-518a-4576-bb02-ddf6804173bf)


Lower Band
![Screenshot_20230809_135859](https://github.com/ooples/OoplesFinance.StockIndicators/assets/140293889/bc1849d9-ca48-417b-a296-0a6682fdc8e5)

This can be ONE of the many reasons why Insync Index values produced by the library is incorrect.

**Comment by HamzaAhmedZia7** [comment]
Interestingly enough the bollinger bands values calculated by the python wrapper library ta-lib is matching with the charts on sites like investing.com For eg RELIANCE on Friday August 04, 2023. 

This python code
```
bbands = talib.BBANDS(reliance.close,timeperiod=20,nbdevup=2.0,nbdevdn=2.0,matype=0)
out = pd.DataFrame({'upperband':bb.upperband,'middleband':bb.middleband,'lowerband':bb.lowerband})
out
``` 

produces the following bollinger band values
![Screenshot_20230809_165515](https://github.com/ooples/OoplesFinance.StockIndicators/assets/140293889/f88c69c3-da22-466f-9ff1-5fee5dfb1943)


Which matches investing.com charts
![Screenshot_20230809_165822](https://github.com/ooples/OoplesFinance.StockIndicators/assets/140293889/2504802a-ad5e-4cd8-9244-2d25929b5cf6)

However it still does not match tradingview charts posted above. 

What is going on here?

Is the calculation methodology adopted by TradingView (pinescript); their runtime different from others?

**Comment by ooples** [comment]
@HamzaAhmedZia7 Well in this case, feel free to take a look at my bollinger band code and see if you spot any issues

**Comment by HamzaAhmedZia7** [comment]
In method public static StockData CalculateStandardDeviationVolatility(this StockData stockData, MovingAvgType maType = MovingAvgType.SimpleMovingAverage, int length = 20)

which is called from CalculateBollingerBands(); the item is being set to the moving average list and not the close price/inputList therefore there is an error

I do not know how to edit and fix nuget packages. I tried doing the following change however while debugging VS always picks up your nuget package. Wasted an hour trying to debug with my changes in vain.

```
//List<double> item = CalculationsHelper.GetInputValuesList(stockData).inputList;
List<double> item = stockData.ClosePrices;
```

I cannot investigate further since I cannot change nuget source code or maybe I do not know how to....

Hopefully this will take you in the right direction.

Also there are straight forward ways of calculating std deviations. Why have you taken such a convoluted approach.

```
public static class Extend
{
    public static double StandardDeviation(this IEnumerable<double> values)
    {
        double avg = values.Average(); 
        return Math.Sqrt(values.Average(v=>(v-avg) * (v-avg)));
    }
}
```

I would highly recommend not to reinvent the wheel and use one of the better open source math libraries Math.NET 

```
Install-Package MathNet.Numerics
```

```
var populationStdDev = new List<double>(1d, 2d, 3d, 4d, 5d).PopulationStandardDeviation();

var sampleStdDev = new List<double>(2d, 3d, 4d).StandardDeviation();
```
[DescriptiveStatistics](http://numerics.mathdotnet.com/docs/DescriptiveStatistics.html)

**Comment by ooples** [comment]
@HamzaAhmedZia7 A couple of things I need to clarify with you. I do my own standard deviation calculation because it is used as a stock indicator and is also used by multiple technical analysis calculations and the code you posted above will fail since it doesn't handle potential errors like doing a square root for a negative number or checking that the values list has items for example. 

You can view the full source code for my library by going to the main code tab and click on the green code button that will allow you to download my full source code. 

I have no clue what you mean about it being set to the moving average list and not using the input list so you will need to elaborate on that.

**Comment by HamzaAhmedZia7** [comment]
@ooples 

>  code you posted above will fail 

Obviously I wasn't trying to fully understand the architectural decisions you took and the reasons for using such a round about method. I just wanted to check for a quick fix. If it had worked I would have pointed out the trivial resolution for you to elaborately fix it. ;-)

> since it doesn't handle potential errors like doing a square root for a negative number or checking that the values list has items for example.

Checking for these are trivial

> I have no clue what you mean about it being set to the moving average list and not using the input list so you will need to elaborate on that.

In function CalculateStandardDeviationVolatility which is called from CalculateBollingerBands(); 
while debugging I found that item = CalculationsHelper.GetInputValuesList(stockData).inputList; 
is being incorrectly set to the simple moving average of the close price inplace of the close prices.

I presume you are trying to set item to the list of close prices for the security. That is discrepency I found and after that being a nuget package could not go further.  Hope this points you to the right direction.

![Screenshot_20230809_215911](https://github.com/ooples/OoplesFinance.StockIndicators/assets/140293889/1adb8742-4909-44bd-8c78-9c7d843c99c2)

> You can view the full source code for my library by going to the main code tab and click on the green code button that will allow you to download my full source code.

Possibly some other time
